---
kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/lxbot/adapter-slack

steps:
  - name: docker
    image: plugins/docker
    settings:
      repo: lxbot/adapter-slack
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    when:
      branch:
        - master